### PR TITLE
correct spelling

### PR DESCRIPTION
**Pull request by audunstrand**
FIaaS changed to Fiaas

### CODE REVIEW

**Review by 3lvis — APPROVED** [review]

**Comment by 3lvis** [comment]
Nice catch, Audun!

**Comment by theneva** [comment]
How can that possibly be the correct styling? :P

**Comment by theneva** [comment]
I'll agree to FiaaS, but Fiaas? What

**Comment by 3lvis** [comment]
@theneva works for me as well :)

**Comment by audunstrand** [comment]
I made the name, I know :)
Its either fiaas or FIAAS. Fiaas if it would normally have a capital letter

**Comment by theneva** [comment]
I yield, and prefer "fiaas" :D

**Comment by trygve-lie** [comment]
FIaaS if one follow the XaaS acronym norm.

**Comment by SimenB** [comment]
It's not an acronym anymore though, is it?

**Comment by trygve-lie** [comment]
If not an acronym? https://github.com/finn-no/finn-no.github.com/blob/master/index.html#L75.

**Comment by SimenB** [comment]
There was some talk about just making it a name as it's being used in more than finn. @mortenlj is it still an acronym, or is it just a name now? If it's still an acronym, will that change?

**Comment by mortenlj** [comment]
It started out as a backronym, but the expanded version never really made any sense (like most backronyms), so we have for a while just thought of it as a simple name without further meaning. There is probably lots of places where this is not reflected, such as in this repo.

When it comes to the spelling, I have always used FiaaS, but I don't really care that much, and I certainly don't know what the "right" spelling would be. :stuck_out_tongue:

**Comment by theneva** [comment]
Let's just go with "fiaas" as per Audun's instructions then? :)

**Comment by oyvindio** [comment]
Personally I prefer, and use FIAAS. Not even the internal documentation seems to agree about this, but most of it (not all :)) seems to use FIAAS.

**Comment by 3lvis** [comment]
Since it's an acronym I think the correct spelling would be FIAAS.

**Comment by theneva** [comment]
It's not really an acronym anymore, it's just "fiaas" as a common component across Schibsted

**Pull request merged**
